
package com.elfy.TaskCreator.gui;

import com.elfy.TaskCreator.Utils.RandomPasswordGenerator;
import com.elfy.TaskCreator.mail.EmailSessionBean;
import java.awt.CardLayout;


public class Main extends javax.swing.JFrame {
    
    //layout declaration
    private CardLayout layout = new CardLayout();
    
    
    //Related Objects
    private RandomPasswordGenerator rpg = new RandomPasswordGenerator();
    private EmailSessionBean esb = new EmailSessionBean();
    
    
    //Mail Variables
    private String message = "Hello :) and thanks for using TaskCreator , you password is here "+rpg.createPassword()+" Use it to log in the application";
    private String subject = "TaskCreator , login acces ";
                                    
    
    public Main() {
        initComponents();
        //adding panels to the main one
        jPanel1.setLayout(layout);
        jPanel1.add("LoginScreen",panelLogin_Screen);
        jPanel1.add("SignUpScreen",panelSignup_form);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelLogin_Screen = new javax.swing.JPanel();
        labelLoginPicture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textLoginUserName = new javax.swing.JTextField();
        labelLoginPassword = new javax.swing.JLabel();
        textLoginPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        buttonSignup = new javax.swing.JButton();
        panelSignup_form = new javax.swing.JPanel();
        labelNameSignUp = new javax.swing.JLabel();
        textNameSignUp = new javax.swing.JTextField();
        labelUserNameSignUp = new javax.swing.JLabel();
        textUserNameSignUp = new javax.swing.JTextField();
        labelUserEmailSignUp = new javax.swing.JLabel();
        textUserEmailSignUp = new javax.swing.JTextField();
        buttonOkSignUp = new javax.swing.JButton();
        labelUserNameMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        labelLoginPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("User Name");

        labelLoginPassword.setText("Password");

        textLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLoginPasswordActionPerformed(evt);
            }
        });

        buttonLogin.setText("Login");

        buttonSignup.setText("Sign-up");
        buttonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLogin_ScreenLayout = new javax.swing.GroupLayout(panelLogin_Screen);
        panelLogin_Screen.setLayout(panelLogin_ScreenLayout);
        panelLogin_ScreenLayout.setHorizontalGroup(
            panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin_ScreenLayout.createSequentialGroup()
                .addGroup(panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogin_ScreenLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textLoginUserName)
                            .addComponent(textLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                    .addGroup(panelLogin_ScreenLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(buttonLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSignup))
                    .addGroup(panelLogin_ScreenLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(labelLoginPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        panelLogin_ScreenLayout.setVerticalGroup(
            panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin_ScreenLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(labelLoginPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLoginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panelLogin_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonSignup))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jPanel1.add(panelLogin_Screen, "card2");

        labelNameSignUp.setText("Name");

        textNameSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameSignUpActionPerformed(evt);
            }
        });

        labelUserNameSignUp.setText("User Name");

        textUserNameSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserNameSignUpActionPerformed(evt);
            }
        });

        labelUserEmailSignUp.setText("E-mail");

        textUserEmailSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserEmailSignUpActionPerformed(evt);
            }
        });

        buttonOkSignUp.setText("OK");
        buttonOkSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSignup_formLayout = new javax.swing.GroupLayout(panelSignup_form);
        panelSignup_form.setLayout(panelSignup_formLayout);
        panelSignup_formLayout.setHorizontalGroup(
            panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignup_formLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addGroup(panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignup_formLayout.createSequentialGroup()
                        .addComponent(labelUserNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUserNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUserNameMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignup_formLayout.createSequentialGroup()
                        .addComponent(labelNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignup_formLayout.createSequentialGroup()
                        .addComponent(labelUserEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textUserEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonOkSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        panelSignup_formLayout.setVerticalGroup(
            panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignup_formLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignup_formLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUserNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textUserNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignup_formLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelUserNameMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSignup_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUserEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(buttonOkSignUp)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jPanel1.add(panelSignup_form, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLoginPasswordActionPerformed

    private void textNameSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameSignUpActionPerformed

    private void textUserNameSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserNameSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserNameSignUpActionPerformed

    private void textUserEmailSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserEmailSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserEmailSignUpActionPerformed

    private void buttonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignupActionPerformed
        layout.show(jPanel1, "SignUpScreen");
        
        
        
    }//GEN-LAST:event_buttonSignupActionPerformed

    private void buttonOkSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkSignUpActionPerformed
       
        esb.sendEmail(textUserEmailSignUp.getText(), subject, message);
        layout.show(jPanel1,"LoginScreen");
        
    }//GEN-LAST:event_buttonOkSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonOkSignUp;
    private javax.swing.JButton buttonSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLoginPassword;
    private javax.swing.JLabel labelLoginPicture;
    private javax.swing.JLabel labelNameSignUp;
    private javax.swing.JLabel labelUserEmailSignUp;
    private javax.swing.JLabel labelUserNameMessage;
    private javax.swing.JLabel labelUserNameSignUp;
    private javax.swing.JPanel panelLogin_Screen;
    private javax.swing.JPanel panelSignup_form;
    private javax.swing.JPasswordField textLoginPassword;
    private javax.swing.JTextField textLoginUserName;
    private javax.swing.JTextField textNameSignUp;
    private javax.swing.JTextField textUserEmailSignUp;
    private javax.swing.JTextField textUserNameSignUp;
    // End of variables declaration//GEN-END:variables
}
